version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: atenea_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: ateneadb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # We can mount the schema to automatically initialize the database
      - ../atenea_schema.sql:/docker-entrypoint-initdb.d/1_schema.sql

volumes:
  postgres_data:
